apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-bootcamp-db
  name: kubernetes-bootcamp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-bootcamp-db
  strategy: { }
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp-db
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          resources: { }
status: { }
